- name: Deploy QEMU VMs and Setup GitHub Runners on x64
  hosts: fusili
  become: true
  vars:
    arm_runners: false
  roles:
    - host_setup


# - name: Deploy registry
#   hosts: kratos
#   become: true
#   roles:
#     - registry_setup

