- name: Deploy QEMU VMs and Setup GitHub Runners
  hosts: all
  become: true
  vars_files:
    - vars.yml
  roles:
    - qemu_setup

- name: Configure GitHub Actions Runner
  hosts: all
  become: true
  roles:
    - github_runner
