- name: Install dependencies
  apt:
    name:
      - curl
      - jq
      - unzip
      - git
    state: present

- name: Install Docker
  block:
    - name: Install required Docker packages
      apt:
        name:
          - docker.io
          - docker-compose
        state: present
    - name: Enable Docker service
      systemd:
        name: docker
        enabled: yes
        state: started
  when: runner_setup:install_docker

- name: Add user to Docker group
  user:
    name: ubuntu
    groups: docker
    append: yes
  when: runner_setup.install_docker

- name: Install QEMU & Required tools
  apt:
    name:
      - qemu-kvm
      - libvirt-daemon-system
      - virt-manager
      - bridge-utils
    state: present
  when: runner_setup.install_qemu

- name: Add user to kvm group
  user:
    name: ubuntu
    groups: kvm
    append: yes
  when: runner_setup.install_qemu

- name: Enable Nested Virtualisation for KVM
  lineinfile:
    path: /etc/modprobe.d/kvm.conf
    line: 'options kvm_intel nested=1'
    create: yes
  when: runner_setup.optimise_nested_virtualisation

- name: Load Kernel Modules
  shell: modprobe kvm_intel
  when: runner_setup.optimise_nested_virtualisation

- name: Verify Nested Virtualisation is enabled
  shell: cat /sys/module/kvm_intel/parameters/nested
  register: nested_vtx

- name: Debug Nested Virtualisation status
  debug:
    msg: "Nested Virtualisation enabled: {{ nested_vtx.stdout }}"

- name: Restart Runner to apply changes
  reboot:
    reboot_timeout: 300

- name: Create actions runner directory
  file:
    path: /home/ubuntu/actions-runner
    state: directory
    owner: ubuntu
    group: ubuntu

- name: Download GitHub Actions Runner
  get_url:
    url: "https://github.com/actions/runner/releases/latest/download/actions-runner-linux-x64-$(uname -m).tar.gz"
    dest: "/home/ubuntu/actions-runner/actions-runner-linux-x64.tar.gz"

- name: Extract GitHub Actions Runner
  unarchive:
    src: "/home/ubuntu/actions-runner/actions-runner-linux-x64.tar.gz"
    dest: "/home/ubuntu/actions-runner"
    remote_src: yes

- name: Get GitHub runner token
  uri:
    url: "https://api.github.com/repos/{{ github_runner.repo }}/actions/runners/registration-token"
    method: POST
    headers:
      Authorization: "token {{ github_runner.token }}"
      Accept: "application/vnd.github.v3+json"
    return_content: yes
  register: runner_token 

- name: Register GitHub Actions runner
  command: >
    /home/ubuntu/actions-runner/config.sh
    --url https://github.com/{{ github_runner.repo }}
    --token {{ runner_token.json.token }}

- name: Install and start GitHub runner
  command: >
    /home/ubuntu/actions-runner/svc.sh install && /home/ubuntu/actions-runner/svc.sh start
