---
- name: List all VMs
  command: virsh list --all --name
  register: all_vms
  changed_when: false

- name: Extract and save VMs to be created
  set_fact:
    vms_to_be_created: "{{ vms.instances | map(attribute='name') | list }}"

- name: Extract GitHub owner and repo from github_url
  set_fact:
    github_owner: "{{ vms.global.github_runner.url.split('/')[0] }}"
    repo_name: "{{ vms.global.github_runner.url.split('/')[1] if '/' in vms.global.github_runner.url else '' }}"

- name: Get list of GitHub runners
  uri:
    url: >-
      https://api.github.com/{{ 'orgs/' + github_owner if repo_name == '' else 'repos/' + github_owner + '/' + repo_name }}/actions/runners
    method: GET
    headers:
      Authorization: "token {{ vms.global.github_runner.token }}"
      Accept: "application/vnd.github.v3+json"
    return_content: yes
  register: runners_response

- name: Extract current runner names from GitHub
  set_fact:
    current_runner_names: "{{ runners_response.json.runners | map(attribute='name') | list }}"

- name: Print current VMs
  debug:
    var: current_runner_names

- name: Determine new VMs that are not registered as GitHub runners
  set_fact:
    new_runners: "{{ vms_to_be_created | difference(current_runner_names) }}"

- name: Print new VMs
  debug:
    var: new_runners
