- name: Create directory for cloud-init files
  ansible.builtin.file:
    path: "{{ vms.global.cloud_init_server_dir }}/{{ item.name }}"
    state: directory
    mode: '0755'
  loop: "{{ vms.instances }}"

- name: Generate meta-data for each VM
  ansible.builtin.template:
    src: "cloud-init/meta-data.j2"
    dest: "{{ vms.global.cloud_init_server_dir }}/{{ item.name }}/meta-data"
    mode: '0644'
  loop: "{{ vms.instances }}"

- name: Generate connect-runner.sh from template
  ansible.builtin.template:
    src: "cloud-init/connect-runner.sh.j2"
    dest: "{{ vms.global.cloud_init_server_dir }}/connect-runner.sh"
    mode: '0644'

- name: Base64 encode the script and format it
  shell: |
    base64 -w 0 "{{ vms.global.cloud_init_server_dir }}/connect-runner.sh"
  register: encoded_script_output

- name: Generate user-data for each VM
  ansible.builtin.template:
    src: "cloud-init/user-data.j2"
    dest: "{{ vms.global.cloud_init_server_dir }}/{{ item.name }}/user-data"
    mode: '0644'
  loop: "{{ vms.instances }}"
  vars:
    encoded_script: "{{ encoded_script_output.stdout }}"
