- name: Install Required Packages for QEMU & Virtualisation
  apt:
    name:
      - qemu-kvm
      - libvirt-daemon-system
      - virt-manager
      - bridge-utils
      - cloud-utils
      - genisoimage
      - python3-libvirt
      - python3-lxml
    state: present

- name: Install Docker
  block:
    - name: Install Docker packages
      apt:
        name:
          - docker.io
          - docker-compose
        state: present
    - name: Enable Docker service
      systemd:
        name: docker
        enabled: yes
        state: started

- name: Add User to Libvirt and Docker Groups
  user:
    name: "{{ ansible_user_id }}"
    groups: libvirt,docker,kvm
    append: yes

- name: Enable Nested Virtualization on Host
  lineinfile:
    path: /etc/modprobe.d/kvm.conf
    line: 'options kvm_intel nested=1'
    create: yes
  when: ansible_architecture == "x86_64"

- name: Load KVM Module
  shell: modprobe kvm_intel
  when: ansible_architecture == "x86_64"

- name: Verify Nested Virtualization is Enabled
  shell: cat /sys/module/kvm_intel/parameters/nested
  register: nested_vtx

- name: Debug Nested Virtualization Status
  debug:
    msg: "Nested Virtualization Enabled: {{ nested_vtx.stdout }}"

- name: Restart Host System (if necessary)
  reboot:
    reboot_timeout: 300
  when: nested_vtx.stdout == 'N'
